export const countries = [
"All"
,"United States of America"
,"United Kingdom"
,"United Kingdom of Great Britain and Ireland"
,"France"
,"Russian Empire"
,"Germany"
,"India"
,"Wales"
,"Great Britain"
,"Canada"
,"Soviet Union"
,"Ancient Rome"
,"Japan"
,"Australia"
,"Kingdom of Italy"
,"Kingdom of England"
,"Republic of Ireland"
,"Austria"
,"Italy"
,"Sweden"
,"Austria-Hungary"
,"Poland"
,"Kingdom of Prussia"
,"Nigeria"
,"Kingdom of the Netherlands"
,"Switzerland"
,"Norway"
,"German Empire"
,"Czechoslovakia"
,"Russian Soviet Federative Socialist Republic"
,"Brazil"
,"Austrian Empire"
,"Classical Athens"
,"Russian Socialist Federative Soviet Republic"
,"Hungary"
,"New Zealand"
,"Denmark"
,"Greece"
,"Weimar Republic"
,"Argentina"
,"Finland"
,"Kingdom of France"
,"Russia"
,"Egypt"
,"Israel"
,"Ottoman Empire"
,"Mexico"
,"People's Republic of China"
,"South Africa"
,"Kingdom of Portugal"
,"Abbasid Caliphate"
,"Holy Roman Empire"
,"German Reich"
,"Nazi Germany"
,"Iran"
,"Socialist Federal Republic of Yugoslavia"
,"Portugal"
,"Kingdom of Denmark"
,"Romania"
,"German Democratic Republic"
,"Turkey"
,"Kingdom of Yugoslavia"
,"Second Polish Republic"
,"Republic of Florence"
,"Chile"
,"Denmark–Norway"
,"Pakistan"
,"Republic of China"
,"Republic of Venice"
,"Estonia"
,"United Arab Republic"
,"Irish Free State"
,"Czech Republic"
,"Byzantine Empire"
,"Lebanon"
,"Kingdom of Ireland"
,"West Germany"
,"Kingdom of Romania"
,"Philippines"
,"Latvia"
,"Ecuador"
,"Netherlands"
,"Kingdom of Württemberg"
,"First Republic of Austria"
,"Russian Republic"
,"Bangladesh"
,"South Korea"
,"Kingdom of Egypt"
,"Polish–Lithuanian Commonwealth"
,"Syria"
,"Kingdom of Saxony"
,"German Confederation"
,"Republic of Egypt (1953–1958)"
,"Peru"
,"Slovenia"
,"Nepal"
,"Taiwan"
,"Iceland"
,"Indonesia"
,"Kingdom of Naples"
,"Kingdom of Majorca"
,"Federal State of Austria"
,"Dutch Republic"
,"Cuba"
,"Crown of Aragon"
,"Republic of German-Austria"
,"Uruguay"
,"Second Syrian Republic"
,"Trinidad and Tobago"
,"French First Republic"
,"Lithuania"
,"Republic of Geneva"
,"Kingdom of Serbia"
,"Constitutional Cabinet of Louis XVI"
,"Colombia"
,"Electorate of Saxony"
,"French Third Republic"
,"Grand Duchy of Finland"
,"Albania"
,"Yugoslavia"
,"Bulgaria"
,"Crown of Castile"
,"Arab Kingdom of Syria"
,"Papal States"
,"Second French Empire"
,"Venezuela"
,"Seljuk Empire"
,"Kingdom of Bavaria"
,"Qajar Iran"
,"Kingdom of Hungary"
,"Polish People's Republic"
,"Zambia"
,"Morocco"
,"Uzbekistan"
,"Iraq"
,"Principality of Serbia"
,"Thailand"
,"Kingdom of Lombardy–Venetia"
,"Kingdom of Bohemia"
,"French mandate of Lebanon"
,"Jamaica"
,"Habsburg monarchy"
,"Democratic Federal Yugoslavia"
,"Ghana"
,"British Empire"
,"Algeria"
,"Samanid Empire"
,"Empire of Japan"
,"Kingdom of Serbs, Croats and Slovenes"
,"Croatia"
,"Vietnam"
,"Kingdom of Hanover"
,"Kenya"
,"Ghaznavid Empire"
,"Alawite State"
,"Grand Duchy of Tuscany"
,"State of Greater Lebanon"
,"Tibet"
,"Ukrainian People's Republic"
,"Ukrainian Soviet Socialist Republic"
,"Joseon"
,"United Principalities of Moldavia and Wallachia"
,"Kingdom of Scotland"
,"Zimbabwe"
,"Senegal"
,"Byelorussian Soviet Socialist Republic"
,"North Korea"
,"Sri Lanka"
,"Federal People's Republic of Yugoslavia"
,"Principality of Moldavia"
,"Empire of Brazil"
,"Grand Duchy of Mecklenburg-Schwerin"
,"Belarus"
,"Pahlavi Iran"
,"Brandenburg-Prussia"
,"Tunisia"
,"Bolivia"
,"Socialist Republic of Romania"
,"mandatory Lebanese Republic"
,"Singapore"
,"Federation of Nigeria"
,"Seventeen Provinces"
,"Confederation of the Rhine"
,"French protectorate of Tunisia"
,"Congress Poland"
,"Kingdom of Toledo"
,"Haiti"
,"Yemen"
,"Federal Republic of Yugoslavia"
,"Ostrogothic Kingdom"
,"Free City of Danzig"
,"Jordan"
,"Malta"
,"Duchy of Schleswig"
,"Grand Duchy of Lithuania"
,"Archduchy of Austria"
,"Chu"
,"Almoravid dynasty"
,"State of Syria"
,"Botswana"
,"Saudi Arabia"
,"Spanish Empire"
,"Mamluk Sultanate"
,"Grand Duchy of Hesse"
,"Korean Empire"
,"Nicaragua"
,"Electorate of Hesse"
,"Umayyad Caliphate"
,"Uganda"
,"Timurid Empire"
,"Buyid dynasty"
,"Ivory Coast"
,"Union between Sweden and Norway"
,"Union of South Africa"
,"Republic of Genoa"
,"Kingdom of Aragon"
,"First Czechoslovak Republic"
,"Mughal Empire"
,"Carolingian Empire"
,"Kyrgyzstan"
,"Tokugawa shogunate"
,"Democratic Republic of Georgia"
,"Dominica"
,"Safavid Empire"
,"State of Damascus"
,"Crown of the Kingdom of Poland"
,"Duchy of Milan"
,"Dutch East Indies"
,"Grand Duchy of Baden"
,"Guatemala"
,"Kingdom of Sicily"
,"Republic of Ragusa"
,"Saint Lucia"
,"Southern Netherlands"
,"El Salvador"
,"Serbia and Montenegro"
,"Mongolia"
,"Duchy of Florence"
,"Almohad Caliphate"
,"Vatican City"
,"Boeotian confederation"
,"Tsardom of Russia"
,"Palestine"
,"Kingdom of Iraq"
,"Cape Verde"
,"Cao Wei"
,"Kingdom of Northumbria"
,"Kingdom of Poland"
,"Mali"
,"Dominion of Ceylon"
,"Dominican Republic"
,"Myanmar"
,"Kingdom of Tlemcen"
,"Tanzania"
,"First French Empire"
,"Kuru Kingdom"
,"Ilkhanate"
,"Cameroon"
,"Parthian Empire"
,"Somalia"
,"Angola"
,"Honduras"
,"Ethiopia"
,"Slovakia"
,"Sasanian Empire"
,"Sudan"
,"Carthage"
,"Achaemenid Empire"
,"Kingdom of the Two Sicilies"
,"Costa Rica"
,"Seleucid Empire"
,"Guyana"
,"Principality of Wallachia"
,"Cyprus"
,"First Republic of Armenia"
,"Confederate States of America"
,"Mongol Empire"
,"Judah"
,"Iraqi Republic (1958–1968)"
,"Hamburg"
,"Qi"
,"Saint Kitts and Nevis"
,"Kingdom of Nepal"
,"Old Swiss Confederacy"
,"Azerbaijan"
,"Ionian League"
,"Ifriqiya"
,"Han dynasty"
,"Francia"
,"Kingdom of the Lombards"
,"Emirate of Granada"
,"Guinea"
,"Shaki Khanate"
,"Mozambique"
,"Gran Colombia"
,"Kingdom of Navarre"
,"Italian Social Republic"
,"Kingdom of Montenegro"
,"Greater Khorasan"
,"Kazakhstan"
,"Libya"
,"Duchy of Savoy"
,"Khwarezmian Empire"
,"Second Spanish Republic"
,"Duchy of Normandy"
,"Grand Duchy of Moscow"
,"County of Flanders"
,"Gold Coast"
,"Spain under the Restoration"
,"Kingdom of Valencia"
,"Kingdom of Glywysing"
,"North Vietnam"
,"Republic of the Congo"
,"Taifa of Seville"
,"Taiping Heavenly Kingdom"
,"Free City of Frankfurt"
,"The Gambia"
,"Caliphate of Córdoba"
,"Benin"
,"Basutoland"
,"Bahrain"
,"First Saudi State"
,"Kara-Khanid Khanate"
,"Fatimid Caliphate"
,"Andorra"
,"Ancient Egypt"
,"Kingdom of Mercia"
,"West Ukrainian People's Republic"
,"Prince-Bishopric of Montenegro"
,"Kingdom of Castile"
,"Kushan Empire"
,"Lands of the Crown of Saint Stephen"
,"Habsburg Netherlands"
,"Ryukyu Kingdom"
,"Liberia"
,"Imperial China"
,"Ba'athist Iraq"
,"Malawi"
,"United Provinces of Central Italy"
,"Swedish Pomerania"
,"Free Territory of Trieste"
,"North German Confederation"
,"Provincia Libre de Guayaquil"
,"State of Aleppo"
,"Republic of Pisa"
,"Emirate of Bukhara"
,"Đại Việt"
,"Vijayanagara Empire"
,"Margraviate of Brandenburg"
,"Icelandic Commonwealth"
,"Czechoslovak Socialist Republic"
,"Duchy of Mirandola"
,"Western Roman Empire"
,"Kingdom of Jerusalem"
,"Duchy of Lorraine"
,"Kingdom of Spain"
,"Kingdom of Candia"
,"Qatar"
,"Russian state 1918-1920"
,"Cambodia"
,"County of Lippe"
,"Ottoman Syria"
,"Hen Ogledd"
,"Electorate of Mainz"
,"Duchy of Prussia"
,"Pallava dynasty"
,"Macedonia"
,"Pandya dynasty"
,"First Syrian Republic"
,"Khanate of Khiva"
,"Taifa of Córdoba"
,"Oman"
,"Ukrainian State"
,"Empire of Harsha"
,"Goryeo"
,"Kievan Rus'"
,"Kingdom of Croatia"
,"Kingdom of Armenia"
,"Kingdom of Albania"
,"Kingdom of Galicia"
,"Kingdom of Georgia"
,"Kingdom of Hawaiʻi"
,"Kingdom of Hejaz"
,"Khanate of Kazan"
,"Kingdom of Israel"
,"Kingdom of Kartli"
,"Kingdom of León"
,"Kingdom of Nejd and Hejaz"
,"Kingdom of Rheged"
,"Hoysala Empire"
,"Adal Sultanate"
,"Kingdom of Strathclyde"
,"Kingdom of Wessex"
,"Herodian Kingdom of Judea"
,"Kition"
,"Kosovo"
,"Kurdistan"
,"Habsburg Spain"
,"Lagash"
,"Lands of the Bohemian Crown"
,"Liechtenstein"
,"Gupta Empire"
,"Lithuanian–Belorussian Soviet Socialist Republic"
,"Lohara dynasty"
,"Grenada"
,"Manchukuo"
,"Margraviate Hachberg-Sausenberg"
,"Marinid dynasty"
,"Maurya Empire"
,"Montenegro"
,"Muzaffarids of Iran"
,"Najd"
,"Ghurid Empire"
,"Gandhara"
,"Nguyen dynasty"
,"Gahadavala"
,"Niger"
,"French Second Republic"
,"French Indochina"
,"Orange Free State"
,"Orange River Colony"
,"Francoist Spain"
,"First Toungoo Empire"
,"Paraguay"
,"People's Socialist Republic of Albania"
,"Fiji"
,"Erivan Khanate"
,"Prince-Bishopric of Liège"
,"Principality of Antioch"
,"Empire of Nicaea"
,"Principality of Montenegro"
,"Principality of Transylvania"
,"Principality of Tver"
,"Protectorate of Bohemia and Moravia"
,"Prussia"
,"Pundravardhana"
,"Republic of Central Lithuania"
,"East Timor"
,"East Francia"
,"Duchy of Warsaw"
,"Republic of Mulhouse"
,"Republic of New Granada"
,"Republic of Siena"
,"Riograndense Republic"
,"Duchy of Parma and Piacenza"
,"Rus"
,"Duchy of Modena and Reggio"
,"Rwanda"
,"Duchy of Ferrara"
,"Achaean League"
,"Duchy of Brunswick-Lüneburg"
,"Samoa"
,"Duchy of Bavaria"
,"Second Czechoslovak Republic"
,"Djibouti"
,"Delhi Sultanate"
,"Czech and Slovak Federal Republic"
,"Siam"
,"Siberian Republic"
,"Sikh Empire"
,"Silla"
,"Slovak Republic"
,"County of Sicily"
,"Socialist Soviet Republic of Byelorussia"
,"Socialist Soviet Republic of Georgia"
,"Sokoto Caliphate"
,"County of Barcelona"
,"Commonwealth of England"
,"Circassia"
,"State of Brazil"
,"Chola dynasty"
,"Central African Republic"
,"State of Malta"
,"Celtic kingdom of Ireland"
,"Sultanate of Zanzibar"
,"Taifa of Almería"
,"Taifa of Zaragoza"
,"Territory of the Military Commander in Serbia"
,"The Bahamas"
,"Third Czechoslovak Republic"
,"Caere"
,"Togo"
,"Burkina Faso"
,"Transcaucasian Socialist Federative Soviet Republic"
,"Bukharan People's Soviet Republic"
,"British North America"
,"Bornu Empire"
,"Bithynia"
,"Beylik of Tunis"
,"Baekje"
,"Babylonia"
,"Ayyubid Sultanate"
,"United States of the Ionian Islands"
,"Urartu"
,"Artuqids"
,"Armenian Kingdom of Cilicia"
,"Anshan (Persia)"
,"Ancient Carthage"
,"Afghanistan"
,"Kingdom of Burgundy"
,"Kingdom of Asturias"
]