export const countries = [
"All"
,"United States of America"
,"France"
,"Germany"
,"United Kingdom"
,"Poland"
,"Italy"
,"Sweden"
,"Japan"
,"Soviet Union"
,"Canada"
,"United Kingdom of Great Britain and Ireland"
,"Kingdom of the Netherlands"
,"India"
,"Norway"
,"Uruguay"
,"Finland"
,"Kingdom of Italy"
,"Brazil"
,"Russian Empire"
,"Russia"
,"Austria"
,"Czechoslovakia"
,"Hungary"
,"Romania"
,"Switzerland"
,"Israel"
,"Australia"
,"Argentina"
,"Denmark"
,"New Zealand"
,"Czech Republic"
,"People's Republic of China"
,"Portugal"
,"Mexico"
,"Socialist Federal Republic of Yugoslavia"
,"Austria-Hungary"
,"Greece"
,"Slovenia"
,"Turkey"
,"Peru"
,"Great Britain"
,"Iran"
,"South Korea"
,"South Africa"
,"Republic of Ireland"
,"Estonia"
,"Chile"
,"Egypt"
,"Ottoman Empire"
,"German Reich"
,"Indonesia"
,"Austrian Empire"
,"Bulgaria"
,"Kingdom of Portugal"
,"Pakistan"
,"Colombia"
,"Kingdom of England"
,"German Democratic Republic"
,"Kingdom of Yugoslavia"
,"Kingdom of Prussia"
,"Wales"
,"Taiwan"
,"Hamburg"
,"Lithuania"
,"Nigeria"
,"Latvia"
,"German Empire"
,"Ancient Rome"
,"Netherlands"
,"Venezuela"
,"Iraq"
,"Cuba"
,"Slovakia"
,"Belarus"
,"Morocco"
,"Iceland"
,"Haiti"
,"Lebanon"
,"Republic of China"
,"Algeria"
,"Tunisia"
,"Polish–Lithuanian Commonwealth"
,"Bangladesh"
,"Republic of Venice"
,"Croatia"
,"Syria"
,"Saudi Arabia"
,"Ecuador"
,"Philippines"
,"Thailand"
,"Vietnam"
,"Azerbaijan"
,"Armenia"
,"Russian Socialist Federative Soviet Republic"
,"Byzantine Empire"
,"Grand Duchy of Finland"
,"Holy Roman Empire"
,"Cameroon"
,"Albania"
,"Kingdom of Denmark"
,"Kingdom of Iraq"
,"Crown of Aragon"
,"Kingdom of Hungary"
,"Yugoslavia"
,"Kingdom of Serbs, Croats and Slovenes"
,"Jordan"
,"Second Polish Republic"
,"Kingdom of France"
,"Bolivia"
,"Singapore"
,"Costa Rica"
,"Ghana"
,"Weimar Republic"
,"Dutch Republic"
,"French protectorate of Tunisia"
,"Iraqi Republic (1958–1968)"
,"Sri Lanka"
,"Nepal"
,"Abbasid Caliphate"
,"Nazi Germany"
,"Yemen"
,"Joseon"
,"Malta"
,"Papal States"
,"Dominican Republic"
,"Guatemala"
,"Ba'athist Iraq"
,"Kenya"
,"Second Syrian Republic"
,"United Arab Republic"
,"Kingdom of Saxony"
,"Democratic Republic of Georgia"
,"Senegal"
,"Irish Free State"
,"Kazakhstan"
,"Russian Soviet Federative Socialist Republic"
,"Uganda"
,"Afghanistan"
,"Paraguay"
,"Kingdom of Egypt"
,"Ukrainian People's Republic"
,"Kingdom of Bavaria"
,"West Germany"
,"Democratic Republic of the Congo"
,"El Salvador"
,"Classical Athens"
,"Jamaica"
,"Libya"
,"Ethiopia"
,"Sudan"
,"Cyprus"
,"Kingdom of Romania"
,"Republic of Egypt (1953–1958)"
,"Free Hanseatic City of Bremen"
,"Zimbabwe"
,"Myanmar"
,"Kingdom of Württemberg"
,"Russian Republic"
,"Kingdom of Ireland"
,"Guinea"
,"Nicaragua"
,"Ivory Coast"
,"Honduras"
,"Kingdom of Scotland"
,"Trinidad and Tobago"
,"Grand Duchy of Lithuania"
,"Byelorussian Soviet Socialist Republic"
,"Qajar Iran"
,"Benin"
,"Somalia"
,"Angola"
,"Arab Kingdom of Syria"
,"West Ukrainian People's Republic"
,"German Confederation"
,"Polish People's Republic"
,"Kingdom of Naples"
,"Habsburg monarchy"
,"Ukrainian Soviet Socialist Republic"
,"State of Syria"
,"Uzbekistan"
,"Mali"
,"Republic of Geneva"
,"United Arab Emirates"
,"Crown of Castile"
,"First Syrian Republic"
,"Mozambique"
,"Niger"
,"Congress Poland"
,"Kingdom of Bohemia"
,"Mongolia"
,"Republic of the Congo"
,"Tanzania"
,"Kingdom of the Two Sicilies"
,"Grand Duchy of Tuscany"
,"Kingdom of Serbia"
,"Southern Netherlands"
,"Madagascar"
,"Montenegro"
,"Tokugawa shogunate"
,"Safavid Empire"
,"Burkina Faso"
,"State of Damascus"
,"French mandate of Lebanon"
,"Rwanda"
,"Republic of Florence"
,"Qatar"
,"Tajikistan"
,"Cambodia"
,"Empire of Japan"
,"Togo"
,"Bahrain"
,"Kyrgyzstan"
,"Pahlavi Iran"
,"Ukrainian State"
,"Free Territory of Trieste"
,"Mughal Empire"
,"Tsardom of Russia"
,"Cape Verde"
,"Guyana"
,"North Korea"
,"Palestine"
,"Kingdom of Hanover"
,"Principality of Serbia"
,"Kingdom of Nejd and Hejaz"
,"Kingdom of Lombardy–Venetia"
,"Oman"
,"Botswana"
,"Electorate of Saxony"
,"Kingdom of Poland"
,"Federal People's Republic of Yugoslavia"
,"Grand Duchy of Baden"
,"Kingdom of Sicily"
,"Habsburg Netherlands"
,"Principality of Transylvania"
,"Umayyad Caliphate"
,"Kingdom of Aragon"
,"Imperial China"
,"Malawi"
,"Namibia"
,"Tibet"
,"Principality of Moldavia"
,"The Gambia"
,"Republic of Ragusa"
,"Federal Republic of Yugoslavia"
,"Mauritania"
,"Sierra Leone"
,"Carolingian Empire"
,"Kosovo"
,"Spanish Empire"
,"Francia"
,"French First Republic"
,"Republic of Genoa"
,"Serbia and Montenegro"
,"Dutch East Indies"
,"Andorra"
,"Zambia"
,"Eritrea"
,"First Republic of Austria"
,"French Third Republic"
,"Cao Wei"
,"State of Malta"
,"Chad"
,"Papua New Guinea"
,"Duchy of Milan"
,"First French Empire"
,"Socialist Republic of Romania"
,"Beylik of Tunis"
,"First Republic of Armenia"
,"Seljuk Empire"
,"County of Flanders"
,"Principality of Wallachia"
,"United Principalities of Moldavia and Wallachia"
,"Emirate of Nejd and Hasa"
,"Grand Duchy of Mecklenburg-Schwerin"
,"Grand Duchy of Hesse"
,"Kingdom of Spain"
,"Liberia"
,"North German Confederation"
,"Korean Empire"
,"Transylvania"
,"Galicia"
,"Armenian Soviet Socialist Republic"
,"Samanid Empire"
,"Mamluk Sultanate"
,"Liechtenstein"
,"British Empire"
,"First Czechoslovak Republic"
,"Kingdom of Galicia"
,"Turkmenistan"
,"French Indochina"
,"Almoravid dynasty"
,"Republic of German-Austria"
,"Bohemia"
,"Prince-Bishopric of Liège"
,"Kingdom of Sardinia"
,"Kingdom of Toledo"
,"State of Greater Lebanon"
,"State of Aleppo"
,"Burundi"
,"Duchy of Savoy"
,"Confederation of the Rhine"
,"Crown of the Kingdom of Poland"
,"Laos"
,"Archduchy of Austria"
,"Rashidun Caliphate"
,"Ghaznavid Empire"
,"Protectorate of Bohemia and Moravia"
,"Bhutan"
,"Emirate of Granada"
,"Fiji"
,"First Saudi State"
,"Duchy of Warsaw"
,"Czechoslovak Socialist Republic"
,"Sweden-Finland"
,"Kingdom of Navarre"
,"Electorate of Hesse"
,"East Timor"
,"Batavian Republic"
,"Republic of Central Lithuania"
,"Kingdom of Hejaz"
,"Guinea-Bissau"
,"Goryeo"
,"Azerbaijan Soviet Socialist Republic"
,"Grenada"
,"Sasanian Empire"
,"Ifriqiya"
,"Saint Lucia"
,"Ilkhanate"
,"Confederate States of America"
,"Union of South Africa"
,"Timurid Empire"
,"Duchy of Modena and Reggio"
,"Normandy"
,"Denmark–Norway"
,"Democratic Federal Yugoslavia"
,"São Tomé and Príncipe"
,"Kingdom of Castile"
,"Federal State of Austria"
,"Macedonia"
,"Fatimid Caliphate"
,"Han dynasty"
,"Rengency of Algiers"
,"Lordship of Bologna"
,"Kingdom of Greece"
,"Anglo-Egyptian Sudan"
,"Kingdom of Galicia and Lodomeria"
,"Company rule in India"
,"Khwarezmian Empire"
,"Kurdistan"
,"Najd"
,"Brunei"
,"Western Roman Empire"
,"Dominica"
,"Emirate of Bukhara"
,"Alawite State"
,"Almohad Caliphate"
,"Independent State of Croatia"
,"Macau"
,"Republic of Vietnam"
,"Caliphate of Córdoba"
,"Samoa"
,"United Kingdom of the Netherlands"
,"Hispanic Monarchy"
,"Vatican City"
,"Kingdom of Valencia"
,"Buyid dynasty"
,"Lesotho"
,"Republic of Artsakh"
,"Seventeen Provinces"
,"Carthage"
,"Maldives"
,"Empire of Brazil"
,"Grand Duchy of Moscow"
,"Seleucid Empire"
,"Central African Republic"
,"Achaemenid Empire"
,"Kingdom of Armenia"
,"Cook Islands"
,"People's Republic of Bulgaria"
,"Duchy of Prussia"
,"Ottoman Syria"
,"Visigothic Kingdom"
,"Vijayanagara Empire"
,"Kingdom of Bulgaria"
,"North Vietnam"
,"Ancient Egypt"
,"Second Bulgarian Empire"
,"Cape Colony"
,"Bithynia"
,"Kingdom of Northumbria"
,"County of Barcelona"
,"Antigua and Barbuda"
,"Hoysala Empire"
,"Kievan Rus'"
,"Chu"
,"Prussia"
,"Ptolemaic Kingdom"
,"emirate of Córdoba"
,"British rule in Myanmar"
,"Second French Empire"
,"Greater Khorasan"
,"Ostrogothic Kingdom"
,"Solomon Islands"
,"Duchy of Nassau"
,"Qi"
,"Principality of Catalonia"
,"Duchy of Anhalt"
,"Duchy of Lorraine"
,"Free City of Frankfurt"
,"Commonwealth of England"
,"Duchy of Florence"
,"Taifa of Almería"
,"Kingdom of Nepal"
,"Duchy of Schleswig"
,"Kingdom of Majorca"
,"Constitutional Cabinet of Louis XVI"
,"Kathiri Sultanate"
,"The Bahamas"
,"Saint Kitts and Nevis"
,"South Sudan"
,"Russian state 1918-1920"
,"State of Brazil"
,"Silla"
,"Duchy of Brunswick-Lüneburg"
,"Taifa of Seville"
,"Portuguese Empire"
,"Siam"
,"Brandenburg-Prussia"
,"United States of the Ionian Islands"
,"Kingdom of Hawaiʻi"
,"Socialist Soviet Republic of Byelorussia"
,"Mongol Empire"
,"Lithuanian–Belorussian Soviet Socialist Republic"
,"Bukharan People's Soviet Republic"
,"Slovak Republic"
,"Margraviate of Brandenburg"
,"Erivan Khanate"
,"Ethiopian Empire"
,"mandatory Lebanese Republic"
,"Judah"
,"Kingdom of Montenegro"
,"Taiping Heavenly Kingdom"
,"Prince-Bishopric of Montenegro"
,"Second Czechoslovak Republic"
,"Đại Việt"
,"Kingdom of Georgia"
,"Duchy of Parma and Piacenza"
,"Shirvanshahs' State"
,"Republic of Siena"
,"Transcaucasian Socialist Federative Soviet Republic"
,"Holland"
,"Icelandic Commonwealth"
,"Islamic Republic of Afghanistan"
,"Gold Coast"
,"Kara-Khanid Khanate"
,"Khanate of Khiva"
,"Free City of Kraków"
,"Free City of Danzig"
,"Kingdom of Jerusalem"
,"Kingdom of Kartli"
,"Federal Republic of Central America"
,"Far Eastern Republic"
,"Kiribati"
,"Empire of Trebizond"
,"Manchukuo"
,"Marinid dynasty"
,"Electorate of Mainz"
,"Electorate of Bavaria"
,"Nauru"
,"Nguyen dynasty"
,"Duchy of Normandy"
,"Northern Netherlands"
,"Pala Empire"
,"Pallava dynasty"
,"Pandya dynasty"
,"Duchy of Ferrara"
,"Principality of Bulgaria"
,"Principality of Montenegro"
,"Republic of Lucca"
,"Republic of New Granada"
,"Circassia"
,"Ryukyu Kingdom"
,"Sikh Empire"
,"Socialist Soviet Republic of Georgia"
,"Sokoto Caliphate"
,"Somaliland"
,"Burgundian Netherlands"
,"Brittany"
,"British North America"
,"Sultanate of Zanzibar"
,"Taifa of Córdoba"
,"Taifa of Zaragoza"
,"Ayyubid Sultanate"
,"Union between Sweden and Norway"
,"Đại Cồ Việt"
,"Duchy of Bavaria"
,"Third Czechoslovak Republic"
,"Republic of the Congo (Léopoldville)"
,"Tibetan Empire"
,"Majapahit"
,"Kingdom of Etruria"
,"Spain under the Restoration"
,"Kingdom of the Lombards"
,"Free Imperial City of Strasbourg"
,"Zaire"
,"Babylonia"
,"Free State of Prussia"
,"Ayyubid dynasty"
,"Kingdom of Wessex"
,"Hamdanid dynasty"
,"Ashikaga shogunate"
,"Chola dynasty"
,"Djibouti"
,"Armenian Kingdom of Cilicia"
,"Hen Ogledd"
,"Shaki Khanate"
,"French Fourth Republic"
,"Kingdom of Asturias"
,"Chagatai Khanate"
,"Orange Free State"
,"United Kingdom of Portugal, Brazil and the Algarves"
,"Old Swiss Confederacy"
,"Duchy of Teschen"
,"Dominion of Ceylon"
,"Lohara dynasty"
,"Republic of Prekmurje"
,"People's Socialist Republic of Albania"
,"Urartu"
,"Palau"
,"Gandhara"
,"Moldavian Democratic Republic"
,"Ancient Carthage"
,"Vichy France"
,"Ganja khanate"
,"Cisalpine Republic"
,"Italian Social Republic"
,"Estado Novo"
,"Taifa of Granada"
,"Kushan Empire"
,"Gran Colombia"
,"Margraviate of Moravia"
,"Second Spanish Republic"
,"Kingdom of León"
,"Czech and Slovak Federal Republic"
,"County of Sicily"
,"County of Roussillon"
,"County of Lippe"
,"Delhi Sultanate"
,"Kuban People's Republic"
,"Principality of Ansbach"
,"West Francia"
,"People's Republic of Hungary"
,"Bornu Empire"
,"Boeotian confederation"
,"Territory of the Military Commander in Serbia"
,"First Toungoo Empire"
,"Kingdom of Israel"
,"Republic of Mulhouse"
,"Kingdom of Granada"
,"Kingdom of Glywysing"
,"Basutoland"
,"Herodian Kingdom of Judea"
,"Baekje"
,"Kingdom of Croatia"
,"Artuqids"
,"Kingdom of Candia"
,"Kingdom of Burgundy"
,"Anshan (Persia)"
,"Anhalt-Bernburg"
,"French Second Republic"
,"Kingdom of Albania"
,"United Provinces of Central Italy"
,"Khanate of Kazan"
,"United States of Belgium"
,"Gahadavala"
,"July Monarchy"
,"Johor Sultanate"
,"Ghurid Empire"
,"Q25934646"
,"Q1793177"
,"Crimean Regional Government"
,"Pundravardhana"
,"Provincia Libre de Guayaquil"
,"Principality of Tver"
,"Principality of Turov and Pinsk"
,"Principality of Antioch"
,"Prince-Bishopric of Speyer"
,"Israelites"
,"Francoist Spain"
,"Golden Horde"
,"Republic of Pisa"
,"Republic of Upper Volta"
,"Riograndense Republic"
,"Peloponnesian League"
,"Rus"
,"Parthian Empire"
,"Duchy of Mirandola"
,"Russian State"
,"Orange River Colony"
,"Akkadian empire"
,"Dzungar Khanate"
,"East Francia"
,"Muzaffarids of Iran"
,"Mount Lebanon Mutasarrifate"
,"Maurya Empire"
,"Celtic kingdom of Ireland"
,"Margraviate Hachberg-Sausenberg"
,"Empire of China"
,"Empire of Harsha"
,"Serbian Despotate"
,"Maitraka dynasty"
,"Magna Graecia"
,"Magadha"
,"Siberian Republic"
,"Empire of Nicaea"
,"Adal Sultanate"
,"Erfurter Staat"
,"Lands of the Crown of Saint Stephen"
,"Lands of the Bohemian Crown"
,"Caere"
,"Lagash"
,"Yan"
,"Kuru Kingdom"
,"Ionian League"
,"Achaean League"
,"Kition"
,"Bruneian Empire"
,"European Union"
,"Kingdom of Tungning"
,"Kingdom of Tlemcen"
,"Kingdom of Strathclyde"
,"Federated States of Micronesia"
,"Gupta Empire"
,"Federation of Nigeria"
,"Aceh Sultanate"
,"Finnish Democratic Republic"
,"Kingdom of Rheged"
,"Swedish Pomerania"
,"Bourbon Restoration in France"
,"Bosnia"
,"Kingdom of Pontus"
,"First Portuguese Republic"
,"Huan Chu"
,"Kingdom of Pamplona"
,"Habsburg Spain"
,"Kingdom of Mercia"
]