export const languages = [
    ,"All"
    ,"English"
    ,"German"
    ,"French"
    ,"Italian"
    ,"Polish"
    ,"Spanish"
    ,"Russian"
    ,"Portuguese"
    ,"Swedish"
    ,"Czech"
    ,"Dutch"
    ,"Arabic"
    ,"Latin"
    ,"Japanese"
    ,"Slovene"
    ,"Hebrew"
    ,"Hungarian"
    ,"Norwegian"
    ,"Danish"
    ,"Romanian"
    ,"Turkish"
    ,"Finnish"
    ,"Greek"
    ,"Persian"
    ,"Odia"
    ,"Modern Greek"
    ,"Indonesian"
    ,"Korean"
    ,"American English"
    ,"Chinese"
    ,"Slovak"
    ,"Ukrainian"
    ,"Ancient Greek"
    ,"Esperanto"
    ,"Bulgarian"
    ,"Bengali"
    ,"Yiddish"
    ,"Armenian"
    ,"Belarusian"
    ,"Catalan"
    ,"Estonian"
    ,"Egyptian Arabic"
    ,"Welsh"
    ,"Georgian"
    ,"Latvian"
    ,"Azerbaijani"
    ,"Nigerian Pidgin"
    ,"Breton"
    ,"Gujarati"
    ,"Vietnamese"
    ,"Irish"
    ,"Lithuanian"
    ,"Malayalam"
    ,"Punjabi"
    ,"Marathi"
    ,"Occitan"
    ,"Icelandic"
    ,"Tamil"
    ,"Middle French"
    ,"Telugu"
    ,"Medieval Greek"
    ,"Albanian"
    ,"Sanskrit"
    ,"Kannada"
    ,"Nepali"
    ,"Ottoman Turkish"
    ,"Standard Mandarin"
    ,"Basque"
    ,"Afrikaans"
    ,"Low German"
    ,"Yoruba"
    ,"Thai"
    ,"Bashkir"
    ,"Tatar"
    ,"Upper Sorbian"
    ,"Kazakh"
    ,"Kurdish"
    ,"Assamese"
    ,"Scottish Gaelic"
    ,"Swahili"
    ,"Swiss German"
    ,"Maltese"
    ,"Nynorsk"
    ,"Haitian Creole"
    ,"Uzbek"
    ,"Pashto"
    ,"Chuvash"
    ,"Igbo"
    ,"Mandarin Chinese"
    ,"Old French"
    ,"Santali"
    ,"Tagalog"
    ,"Northern Sami"
    ,"Moroccan Arabic"
    ,"Hausa"
    ,"Romansh"
    ,"Austrian German"
    ,"Serbo-Croatian"
    ,"Syriac"
    ,"West Frisian"
    ,"Classical Chinese"
    ,"Tajik"
    ,"Konkani"
    ,"Venetian"
    ,"Kashmiri"
    ,"Meitei"
    ,"Sindhi"
    ,"Macedonian"
    ,"Standard Taiwanese Mandarin"
    ,"Swiss High German"
    ,"Chechen"
    ,"Medieval Latin"
    ,"Western Armenian"
    ,"Kyrgyz"
    ,"Middle High German"
    ,"Somali"
    ,"Taiwanese Mandarin"
    ,"Canadian English"
    ,"Crimean Tatar"
    ,"Rajasthani"
    ,"Mongolian"
    ,"Tibetan"
    ,"Romani"
    ,"Old Mandarin"
    ,"Galician"
    ,"Sorbian"
    ,"Maithili"
    ,"Dogri"
    ,"Old Occitan"
    ,"Sardinian"
    ,"Kabyle"
    ,"Komi"
    ,"Malay"
    ,"Taiwanese Hokkien"
    ,"Erzya"
    ,"Quechua"
    ,"Burmese"
    ,"Mari"
    ,"Udmurt"
    ,"Lower Sorbian"
    ,"Ossetian"
    ,"Amharic"
    ,"Ho"
    ,"Khmer"
    ,"Yakut"
    ,"Picard"
    ,"Turkmen"
    ,"Moldovan"
    ,"Neapolitan"
    ,"Cantonese"
    ,"Middle English"
    ,"Gallo"
    ,"Israeli (Modern) Hebrew"
    ,"Javanese"
    ,"Réunion Creole"
    ,"Scots"
    ,"Kalmyk"
    ,"Alsatian"
    ,"Māori"
    ,"Biblical Hebrew"
    ,"Fula"
    ,"Papiamento"
    ,"Volapük"
    ,"Algerian Arabic"
    ,"Buryat"
    ,"Ecclesiastical Latin"
    ,"Hindustani"
    ,"Judaeo-Spanish"
    ,"Mesopotamian Arabic"
    ,"Newar"
    ,"Akkadian"
    ,"Friulian"
    ,"Karachay-Balkar"
    ,"Malagasy"
    ,"Old Catalan"
    ,"Rusyn"
    ,"Alemannic"
    ,"Bodo"
    ,"Guarani"
    ,"Ingush"
    ,"Koine Greek"
    ,"Laz"
    ,"Ruthenian"
    ,"Ladin"
    ,"Nahuatl"
    ,"Old English"
    ,"Sinhala"
    ,"Faroese"
    ,"Ido"
    ,"Judeo-Arabic"
    ,"Latgalian"
    ,"Lezgian"
    ,"Modern Standard Arabic"
    ,"Old East Slavic"
    ,"Tswana"
    ,"Cornish"
    ,"Egyptian"
    ,"Karelian"
    ,"Kashubian"
    ,"Lebanese Arabic"
    ,"Shilha"
    ,"Sorani"
    ,"medieval Aragonese"
    ,"Abkhaz"
    ,"Adyghe"
    ,"American Sign Language"
    ,"Bokmål"
    ,"Lombard"
    ,"Manx"
    ,"Moksha"
    ,"Southern Sami"
    ,"Wolof"
    ,"Avar"
    ,"Church Slavonic"
    ,"Corsican"
    ,"Kabardian"
    ,"Nenets"
    ,"Piedmontese"
    ,"Riksmål"
    ,"Sesotho"
    ,"Silesian"
    ,"Tuvan"
    ,"Anglo-Norman"
    ,"Coptic"
    ,"Flemish"
    ,"Ilocano"
    ,"Judeo-Tat"
    ,"Mirandese"
    ,"Old Norse"
    ,"Pali"
    ,"Tigrinya"
    ,"Zulu"
    ,"Akan"
    ,"Cebuano"
    ,"Kildin Sami"
    ,"Kumyk"
    ,"Lingala"
    ,"Mapudungun"
    ,"Middle Dutch"
    ,"Old Tatar"
    ,"Tsonga"
    ,"Twi"
    ,"Xhosa"
    ,"Altai"
    ,"Aymara"
    ,"Chaldean Neo-Aramaic"
    ,"Classical Arabic"
    ,"Classical Armenian"
    ,"Dagbani"
    ,"Dargwa"
    ,"Fon"
    ,"Greenlandic"
    ,"Hiberno-English"
    ,"Interlingua"
    ,"Khakas"
    ,"Kinyarwanda"
    ,"Livonian"
    ,"Luganda"
    ,"Luxembourgish"
    ,"Old Church Slavonic"
    ,"Saraiki"
    ,"Shawiya"
    ,"Sumerian"
    ,"Walloon"
    ,"Balochi"
    ,"Galician-Portuguese"
    ,"Hakka"
    ,"Lule Sami"
    ,"Putonghua"
    ,"Shona"
    ,"Aragonese"
    ,"Aromanian"
    ,"Bhojpuri"
    ,"Chagatai"
    ,"Early New High German"
    ,"Ewe"
    ,"Karakalpak"
    ,"Ligurian"
    ,"Meänkieli"
    ,"Middle Persian"
    ,"Norman"
    ,"Prakrit"
    ,"Sicilian"
    ,"Tahitian"
    ,"Tarifit"
    ,"Traditional Chinese"
    ,"Tulu"
    ,"Uyghur"
    ,"Yue Chinese"
    ,"written Chinese language"
    ,"Bavarian"
    ,"British Sign Language"
    ,"Burgundian"
    ,"Cape Verdean Creole"
    ,"Chukchi"
    ,"Cree"
    ,"Even"
    ,"Evenki"
    ,"Fante"
    ,"Ge'ez"
    ,"Gikuyu"
    ,"Guadeloupean Creole"
    ,"Hawaiian"
    ,"Hittite"
    ,"Innu-aimun"
    ,"Inuktitut"
    ,"Jamaican Patois"
    ,"Karaim"
    ,"Khanty"
    ,"Lak"
    ,"Livvi-Karelian"
    ,"Maldivian"
    ,"Old Persian"
    ,"Phoenician"
    ,"Samoan"
    ,"Sango"
    ,"Silesian German"
    ,"Simplified Chinese"
    ,"Skolt Sami"
    ,"Susu"
    ,"Syrian Arabic"
    ,"Talysh"
    ,"Veps"
    ,"Walser German"
    ,"Zapotec"
    ,"Abaza"
    ,"Ainu"
    ,"Arpitan"
    ,"Awadhi"
    ,"Babylonian"
    ,"Chewa"
    ,"Dargin"
    ,"Dari"
    ,"Drèents"
    ,"Dzongkha"
    ,"Early Modern Spanish"
    ,"Ga"
    ,"Gorani"
    ,"Gullah"
    ,"Judeo-Moroccan"
    ,"Kajkavian"
    ,"Kanuri"
    ,"Kirundi"
    ,"Klingon"
    ,"Kurmanji"
    ,"Kven"
    ,"Lao"
    ,"Levantine Arabic"
    ,"Limburgish"
    ,"Manchu"
    ,"Minangkabau"
    ,"Nzema"
    ,"Punic"
    ,"Sambalpuri"
    ,"Southern Kurdish"
    ,"Stellingwarfs"
    ,"Sundanese"
    ,"Tok Pisin"
    ,"Tweants"
    ,"Võro"
    ,"Waray"
    ,"West Flemish"
    ,"Wu Chinese"
    ,"Arbëresh"
    ,"Balinese"
    ,"Bemba"
    ,"Berrichon"
    ,"Bulgar"
    ,"Cherokee"
    ,"Dakhini"
    ,"Duala"
    ,"Early Modern English"
    ,"English language in England"
    ,"Etruscan"
    ,"French Sign Language"
    ,"Gagauz"
    ,"Gen"
    ,"Gilbertese"
    ,"Gondi"
    ,"Gothic"
    ,"Gronings"
    ,"Guinea-Bissau Creole"
    ,"Gulf Arabic"
    ,"Haryanvi"
    ,"Hiligaynon"
    ,"Hindko"
    ,"Inari Sami"
    ,"Isthmus Zapotec"
    ,"Italian Sign Language"
    ,"Kaqchikel"
    ,"Katharevousa"
    ,"Late Egyptian"
    ,"Low Saxon"
    ,"Luri"
    ,"Luwian"
    ,"Láadan"
    ,"Mandaic"
    ,"Mandinka"
    ,"Maninka"
    ,"Mansi"
    ,"Martinican Creole"
    ,"Mauritian Creole"
    ,"Mazanderani"
    ,"Median"
    ,"Medieval Hebrew"
    ,"Middle Low German"
    ,"Middle Polish"
    ,"Mingrelian"
    ,"Mulgi"
    ,"N'Ko"
    ,"Nauruan"
    ,"Navajo"
    ,"Noongar"
    ,"North Frisian"
    ,"Northern Ndebele"
    ,"Ojibwe"
    ,"Old Egyptian"
    ,"Old High German"
    ,"Old Irish"
    ,"Old Spanish"
    ,"Oromo"
    ,"Pennsylvania German"
    ,"Permyak"
    ,"Poitevin-Saintongeais"
    ,"Portuñol"
    ,"Romagnol"
    ,"Ronga"
    ,"Runyankole"
    ,"Sassarese"
    ,"Shan"
    ,"Sioux"
    ,"Southern Min"
    ,"Standard Algerian Berber"
    ,"Sudanese Arabic"
    ,"Swabian"
    ,"Swazi"
    ,"Tavringer Romani"
    ,"Ter Sami"
    ,"Tera"
    ,"Ugaritic"
    ,"Upper Saxon"
    ,"Urhobo"
    ,"Yucatec Maya"
    ,"written vernacular Chinese"
    ,"Abenaki"
    ,"Aceh"
    ,"Acholi"
    ,"Achomi"
    ,"Achterhooks"
    ,"Adi"
    ,"Aka"
    ,"Algonquin"
    ,"Angevin"
    ,"Angika"
    ,"Arawak"
    ,"Arvanitic"
    ,"Atikamekw"
    ,"Atlantean"
    ,"Auslan"
    ,"Austral"
    ,"Avestan"
    ,"Ayacucho Quechua"
    ,"Bahrani Arabic"
    ,"Bakhtiari-Hakhamanesh"
    ,"Bamum"
    ,"Banat Bulgarian"
    ,"Biblical Greek"
    ,"Bishnupriya Manipuri"
    ,"Blissymbols"
    ,"Bobai dialect"
    ,"Bourbonnais"
    ,"Brazilian Sign Language"
    ,"Bukharian"
    ,"Caddo"
    ,"Campidanese Sardinian"
    ,"Central Bikol"
    ,"Chhattisgarhi"
    ,"Chittagonian"
    ,"Chopi"
    ,"Chuukese"
    ,"Classical French"
    ,"Classical Japanese"
    ,"Common Brittonic"
    ,"Contemporary Latin"
    ,"Cusco Quechua"
    ,"Dakota"
    ,"Dalmatian"
    ,"Dholuo"
    ,"Dolgan"
    ,"Druze Arabic"
    ,"Dungan"
    ,"Early Middle Japanese"
    ,"Eastern Yiddish"
    ,"Edo"
    ,"Elamite"
    ,"Emilian-Romagnol"
    ,"Forest Nenets"
    ,"Gataq"
    ,"German Sign Language"
    ,"Gonja"
    ,"Guianan Creole"
    ,"Gujari"
    ,"Gun"
    ,"Haida"
    ,"Harari"
    ,"Hawaiian Pidgin"
    ,"Hijazi Arabic"
    ,"Hill Mari"
    ,"Hiri Motu"
    ,"Hunsrik"
    ,"Huáyǔ"
    ,"Iazychie"
    ,"Ibanag"
    ,"Ibibio"
    ,"Ibinda"
    ,"Idiom Neutral"
    ,"Idoma"
    ,"Imperial Aramaic"
    ,"Indo-Pakistani Sign Language"
    ,"Interlingue"
    ,"Interslavic"
    ,"Itneg"
    ,"Jebero"
    ,"Jin Chinese"
    ,"Judeo-Yemeni Arabic"
    ,"Judæo-Persian"
    ,"Jurchen"
    ,"Jèrriais"
    ,"Kalanga"
    ,"Kamba"
    ,"Kapampangan"
    ,"Karay-a"
    ,"Karbi"
    ,"Khana"
    ,"Khinalug"
    ,"Khitan"
    ,"Khowar"
    ,"Khuzdûl"
    ,"Khuzestani Arabic"
    ,"Khwarezmian"
    ,"Kichwa"
    ,"Kiga"
    ,"Kongo"
    ,"Konkomba"
    ,"Korandje"
    ,"Kuna"
    ,"Kuria"
    ,"Kusunda"
    ,"K’iche’"
    ,"Lakota"
    ,"Lambadi"
    ,"Law French"
    ,"Limonese Creole"
    ,"Lingua Ignota"
    ,"Lojban"
    ,"Louisiana French"
    ,"Luba-Katanga"
    ,"Macanese Patois"
    ,"Magar"
    ,"Makonde"
    ,"Malecite-Passamaquoddy"
    ,"Marshallese"
    ,"Marwari"
    ,"Mayo"
    ,"Mazatecan"
    ,"Meroitic"
    ,"Mi'kmaq"
    ,"Miao language"
    ,"Middle Burmese"
    ,"Middle Chinese"
    ,"Middle Korean"
    ,"Middle Scots"
    ,"Miskito Coast Creole"
    ,"Missingsch"
    ,"Mohawk"
    ,"Mojave"
    ,"Mozarabic"
    ,"Munichi"
    ,"Muscogee"
    ,"Nafusi"
    ,"Najdi Arabic"
    ,"Nanai"
    ,"Navarrese Romance"
    ,"Navarro-Aragonese"
    ,"Naxi"
    ,"New High German"
    ,"New Latin"
    ,"Ngbandi"
    ,"Nheengatu"
    ,"Nivkh"
    ,"Nizaa"
    ,"Northern Sotho"
    ,"Nov Latin"
    ,"Novial"
    ,"Nupe"
    ,"O'odham"
    ,"Old Arabic"
    ,"Old Azeri"
    ,"Old Chinese"
    ,"Old Dutch"
    ,"Old Tamil"
    ,"Old Ukrainian"
    ,"Omaha–Ponca"
    ,"Omani Arabic"
    ,"Ona"
    ,"Palenquero"
    ,"Panroman"
    ,"Parthian"
    ,"Pattani"
    ,"Pirahã"
    ,"Pitkern"
    ,"Plautdietsch"
    ,"Pohnpeian"
    ,"Pular"
    ,"Qara-Qan Uyghur"
    ,"Quenya"
    ,"Rabha"
    ,"Rinconada Bikol"
    ,"Samaritan Aramaic"
    ,"Serer"
    ,"Seri"
    ,"Shor"
    ,"Shuadit"
    ,"Sillan"
    ,"Sindarin"
    ,"Soninke"
    ,"Sorkhei"
    ,"South Jutlandic"
    ,"Spanglish"
    ,"Sranan Tongo"
    ,"Standard High German"
    ,"Surzhyk"
    ,"Tabasaran"
    ,"Taiwanese Classical Chinese"
    ,"Tamahaq"
    ,"Tangale"
    ,"Tangut"
    ,"Tarahumara"
    ,"Tetum"
    ,"Tharu"
    ,"Tiv"
    ,"Tlingit"
    ,"Toba Qom"
    ,"Tojolab'al"
    ,"Toki Pona"
    ,"Tuareg"
    ,"Tumbuka"
    ,"Tunica"
    ,"Tunisian Arabic"
    ,"Tunni"
    ,"Tupi"
    ,"Turki"
    ,"Turkish Sign Language"
    ,"Tyap"
    ,"Tzotzil"
    ,"Tz’utujil"
    ,"Udege"
    ,"Udi"
    ,"Umbrian"
    ,"Umbundu"
    ,"Uzbeki Arabic"
    ,"Venda"
    ,"Vulgar Latin"
    ,"Wallisian"
    ,"Wayana"
    ,"Wayuu"
    ,"Wiradjuri"
    ,"Xiang"
    ,"Yaghan"
    ,"Yaqui"
    ,"Zazaki"
    ,"classical Sanskrit"
    ,"literary Czech"]