export const langCodes = [
    ,{label:'Afrikaans', value:'af'}
    ,{label:'Arabic', value:'ar'}
    ,{label:'Azerbaijani', value:'az'}
    ,{label:'Balinese', value:'ban'}
    ,{label:'Bavarian', value:'bar'}
    ,{label:'Belarusian', value:'be'}
    ,{label:'Bulgarian', value:'bg'}
    ,{label:'Bengali', value:'bn'}
    ,{label:'Tibetan', value:'bo'}
    ,{label:'Catalan', value:'ca'}
    ,{label:'Chechen', value:'ce'}
    ,{label:'Czech', value:'cs'}
    ,{label:'Welsh', value:'cy'}
    ,{label:'Danish', value:'da'}
    ,{label:'Dagbani', value:'dag'}
    ,{label:'German', value:'de'}
    ,{label:'Greek', value:'el'}
    ,{label:'English', value:'en'}
    ,{label:'Spanish', value:'es'}
    ,{label:'Estonian', value:'et'}
    ,{label:'Basque', value:'eu'}
    ,{label:'Persian', value:'fa'}
    ,{label:'Finnish', value:'fi'}
    ,{label:'French', value:'fr'}
    ,{label:'Irish', value:'ga'}
    ,{label:'Scottish Gaelic', value:'gd'}
    ,{label:'Galician', value:'gl'}
    ,{label:'Hebrew', value:'he'}
    ,{label:'Hungarian', value:'hu'}
    ,{label:'Armenian', value:'hy'}
    ,{label:'Indonesian', value:'id'}
    ,{label:'Icelandic', value:'is'}
    ,{label:'Italian', value:'it'}
    ,{label:'Japanese', value:'ja'}
    ,{label:'Javanese', value:'jv'}
    ,{label:'Georgian', value:'ka'}
    ,{label:'Kashmiri', value:'ks'}
    ,{label:'Macedonian', value:'mk'}
    ,{label:'Malayalam', value:'ml'}
    ,{label:'Mongolian', value:'mn'}
    ,{label:'Moldovan', value:'mo'}
    ,{label:'Maltese', value:'mt'}
    ,{label:'Burmese', value:'my'}
    ,{label:'Nepali', value:'ne'}
    ,{label:'Dutch', value:'nl'}
    ,{label:'Nynorsk', value:'nn'}
    ,{label:'Norwegian', value:'nb'}
    ,{label:'Occitan', value:'oc'}
    ,{label:'Polish', value:'pl'}
    ,{label:'Portuguese', value:'pt'}
    ,{label:'Romanian', value:'ro'}
    ,{label:'Russian', value:'ru'}
    ,{label:'Slovak', value:'sk'}
    ,{label:'Slovene', value:'sl'}
    ,{label:'Somali', value:'so'}
    ,{label:'Albanian', value:'sq'}
    ,{label:'Swedish', value:'sv'}
    ,{label:'Swahili', value:'sw'}
    ,{label:'Uzbek', value:'uz'}
    ,{label:'Vietnamese', value:'vi'}
    ,{label:'Chinese', value:'zh'}
    ]