export const languages = [
    "All"
    ,"English"
    ,"French"
    ,"German"
    ,"Russian"
    ,"Latin"
    ,"Italian"
    ,"American English"
    ,"Spanish"
    ,"Ancient Greek"
    ,"Japanese"
    ,"Arabic"
    ,"Polish"
    ,"Welsh"
    ,"Portuguese"
    ,"Swedish"
    ,"Danish"
    ,"Czech"
    ,"Yiddish"
    ,"Dutch"
    ,"Esperanto"
    ,"Norwegian"
    ,"Hebrew"
    ,"Greek"
    ,"Bengali"
    ,"Nigerian Pidgin"
    ,"Hungarian"
    ,"Chinese"
    ,"Persian"
    ,"Odia"
    ,"Finnish"
    ,"Scots"
    ,"Early Modern English"
    ,"Slovene"
    ,"Malayalam"
    ,"Romanian"
    ,"Modern Greek"
    ,"Tamil"
    ,"Turkish"
    ,"Ukrainian"
    ,"Sanskrit"
    ,"Kannada"
    ,"Occitan"
    ,"Estonian"
    ,"Marathi"
    ,"Korean"
    ,"Old English"
    ,"Middle French"
    ,"Nepali"
    ,"Punjabi"
    ,"Gujarati"
    ,"Khuzdûl"
    ,"Latvian"
    ,"Quenya"
    ,"Sindarin"
    ,"Old Catalan"
    ,"Catalan"
    ,"Standard Mandarin"
    ,"Irish"
    ,"Assamese"
    ,"Belarusian"
    ,"Armenian"
    ,"Igbo"
    ,"Indonesian"
    ,"Georgian"
    ,"Mandarin Chinese"
    ,"Muscogee"
    ,"Telugu"
    ,"Middle English"
    ,"Neapolitan"
    ,"Old French"
    ,"Vietnamese"
    ,"Ottoman Turkish"
    ,"Serbo-Croatian"
    ,"Medieval Greek"
    ,"Yoruba"
    ,"Albanian"
    ,"Bulgarian"
    ,"Nynorsk"
    ,"Uzbek"
    ,"Icelandic"
    ,"Kashmiri"
    ,"Afrikaans"
    ,"Maithili"
    ,"Canadian English"
    ,"New High German"
    ,"Rajasthani"
    ,"Alsatian"
    ,"Konkani"
    ,"Syriac"
    ,"Punic"
    ,"Breton"
    ,"Swiss German"
    ,"Austrian German"
    ,"Lithuanian"
    ,"Tibetan"
    ,"Classical Chinese"
    ,"Dogri"
    ,"Early Modern Spanish"
    ,"Azerbaijani"
    ,"Church Slavonic"
    ,"Middle High German"
    ,"Cantonese"
    ,"Tagalog"
    ,"Thai"
    ,"Slovak"
    ,"Walloon"
    ,"West Frisian"
    ,"Pali"
    ,"Egyptian Arabic"
    ,"Khana"
    ,"Meitei"
    ,"medieval Aragonese"
    ,"Amharic"
    ,"Biblical Hebrew"
    ,"Koine Greek"
    ,"Swiss High German"
    ,"Volapük"
    ,"Basque"
    ,"Sindhi"
    ,"written vernacular Chinese"
    ,"Hausa"
    ,"Nahuatl"
    ,"Tajik"
    ,"Venetian"
    ,"Ilocano"
    ,"Old Norse"
    ,"Santali"
    ,"Bodo"
    ,"Mongolian"
    ,"Swahili"
    ,"Khmer"
    ,"Sardinian"
    ,"Gikuyu"
    ,"Hakka"
    ,"Kurdish"
    ,"Kyrgyz"
    ,"Malay"
    ,"Maltese"
    ,"Old High German"
    ,"Friulian"
    ,"Medieval Latin"
    ,"Old Mandarin"
    ,"Sinhala"
    ,"Xiang"
    ,"Angika"
    ,"Judaeo-Spanish"
    ,"Judeo-Tat"
    ,"Phoenician"
    ,"Tatar"
    ,"Wolof"
    ,"Quechua"
    ,"Ruthenian"
    ,"Scottish Gaelic"
    ,"Alemannic"
    ,"Chagatai"
    ,"Lombard"
    ,"Low German"
    ,"Riksmål"
    ,"Rusyn"
    ,"Fante"
    ,"Hindustani"
    ,"Klingon"
    ,"Nzema"
    ,"Picard"
    ,"Romagnol"
    ,"Traditional Chinese"
    ,"Bashkir"
    ,"Bokmål"
    ,"Burmese"
    ,"Cornish"
    ,"Cree"
    ,"Galician"
    ,"Israeli (Modern) Hebrew"
    ,"Jamaican Patois"
    ,"Láadan"
    ,"Moroccan Arabic"
    ,"N'Ko"
    ,"Old East Slavic"
    ,"Old Egyptian"
    ,"Sesotho"
    ,"Standard Taiwanese Mandarin"
    ,"Anglo-Norman"
    ,"Awadhi"
    ,"Bhojpuri"
    ,"Early New High German"
    ,"Hiri Motu"
    ,"Judeo-Arabic"
    ,"Kazakh"
    ,"Khwarezmian"
    ,"Macedonian"
    ,"Middle Dutch"
    ,"Mohawk"
    ,"Prakrit"
    ,"Tamahaq"
    ,"Tok Pisin"
    ,"Tuareg"
    ,"Western Armenian"
    ,"Xhosa"
    ,"Zulu"
    ,"Algerian Arabic"
    ,"Atlantean"
    ,"Biblical Greek"
    ,"Chaldean Neo-Aramaic"
    ,"Classical Arabic"
    ,"Egyptian"
    ,"Fula"
    ,"Haitian Creole"
    ,"Hawaiian"
    ,"Hawaiian Pidgin"
    ,"Ido"
    ,"Interlingua"
    ,"Javanese"
    ,"Jurchen"
    ,"Kabyle"
    ,"Khitan"
    ,"Lao"
    ,"Lingua Ignota"
    ,"Manx"
    ,"Medieval Hebrew"
    ,"Middle Chinese"
    ,"Middle Low German"
    ,"Middle Polish"
    ,"Māori"
    ,"Newar"
    ,"Northern Sami"
    ,"Old Church Slavonic"
    ,"Old Spanish"
    ,"Pashto"
    ,"Plautdietsch"
    ,"Romani"
    ,"Saraiki"
    ,"Shawiya"
    ,"Somali"
    ,"Standard High German"
    ,"Tarifit"
    ,"Tswana"
    ,"Twi"
    ,"Upper Sorbian"
    ,"Aceh"
    ,"Acholi"
    ,"Akan"
    ,"Akkadian"
    ,"Aragonese"
    ,"Avar"
    ,"Babylonian"
    ,"Balochi"
    ,"Chewa"
    ,"Coptic"
    ,"Dari"
    ,"Elamite"
    ,"Erzya"
    ,"Etruscan"
    ,"Ewe"
    ,"Faroese"
    ,"Fon"
    ,"Galician-Portuguese"
    ,"Greenlandic"
    ,"Gullah"
    ,"Haryanvi"
    ,"Hiberno-English"
    ,"Imperial Aramaic"
    ,"Kalmyk"
    ,"Kashubian"
    ,"Katharevousa"
    ,"Kurmanji"
    ,"Kusunda"
    ,"Ladin"
    ,"Lebanese Arabic"
    ,"Ligurian"
    ,"Limburgish"
    ,"Lojban"
    ,"Meänkieli"
    ,"Middle Burmese"
    ,"Middle Persian"
    ,"Middle Scots"
    ,"Minangkabau"
    ,"Missingsch"
    ,"Mulgi"
    ,"Navajo"
    ,"Navarrese Romance"
    ,"Naxi"
    ,"Noongar"
    ,"Novial"
    ,"Old Chinese"
    ,"Old Dutch"
    ,"Old Persian"
    ,"Old Tamil"
    ,"Papiamento"
    ,"Qara-Qan Uyghur"
    ,"Romansh"
    ,"Réunion Creole"
    ,"Samoan"
    ,"Shona"
    ,"Sicilian"
    ,"Silesian"
    ,"Sillan"
    ,"Simplified Chinese"
    ,"Sioux"
    ,"Sorbian"
    ,"Southern Sami"
    ,"Spanglish"
    ,"Tahitian"
    ,"Taiwanese Hokkien"
    ,"Taiwanese Mandarin"
    ,"Tharu"
    ,"Turkmen"
    ,"Ugaritic"
    ,"Wu Chinese"
    ,"Yue Chinese"
    ,"Zazaki"
]