const labels = {
    born : 'Born',
    died : 'Died',
    nationality : 'Nationality',
    floruit : 'Floruit',
    occupation : 'Occupations',
    other_occupations : 'also known as ',
    wikidesc : '(wikipedia)',
    influence : 'Influences:',
    influenced : 'Influenced:',
    works : 'List of known works',
    unspecified : 'Unknown',
    worksUnknown : 'No known works',
    nativeName : 'Native Name',
    languages : 'Languages ',
    form : 'Form ',
    wiki : 'Wiki ',
    original_title : 'Original Title ',
    written_date : 'Written ',
    language : 'Language ',
    genre : 'Genre ',
    type : 'Type ',
    metre : 'Metre ',
    length : 'Length ',
    publishers : 'Publishers ',
    aka : 'aka.',
    author_name : 'Author',
    original_language : 'Original Language(s)',
    original_publication_date : 'Original Publication',
    original_publisher_name : 'Original Publisher',
    original_publication_type : 'Type',
    original_publication_length : 'Length',
    writing_period : 'Writing period',
    editors : 'Editors',
    publisher : 'Publisher',
    binding : 'Binding',
    pages : 'pages',
    publication : 'Published',
    homeBtn: 'Home',
    latestAdditions: 'New Additions',
    }
    
export default labels;