const labels = {
    born : 'Born',
    died : 'Died',
    nationality : 'Nationality',
    floruit : 'Floruit',
    occupation : 'Occupation',
    other_occupations : 'also known as ',
    wiki : '(wikipedia)',
    influence : 'Influences:',
    influenced : 'Influenced:',
    works : 'List of known works',
    add_works : 'Add works:',
    unspecified : 'not specified',
    submit_edits : 'Submit',
    edit_country_birth_description : ' (city, country) of birth',
    edit_country_death_description : ' (city, country) of death',
    editBtn : 'Edit',
    exitEditBtn : 'Stop Editing',
    worksUnknown : 'No known works',
    aka : 'aka.',
    author_name : 'Author',
    original_language : 'Original Language(s)',
    original_publication_date : 'Original Publication',
    original_publisher_name : 'Original Publisher',
    original_publication_type : 'Type',
    original_publication_length : 'Length',
    writing_period : 'Writing period',
    editions : 'Editions',
    edition_title : 'Title',
    edition_editors : 'Editors',
    edition_language : 'Language',
    isbn : 'ISBN',
    author : 'Author',
    original_title : 'Original Title',
    language : 'Language',
    editors : 'Editors',
    publisher : 'Publisher',
    binding : 'Binding',
    pages : 'pages',
    publication : 'Published',
    length : 'Length',
    import_header : 'Data Import',
    import_type : 'Please select import type',
    import_type_select : 'Import type',
    import_preview_header : 'Preview',
    import_upload_data : 'Upload data',
    import_preview_label : 'Please change column names using the dropdowns',
    import_push_data : 'Push data to database',
    import_refresh : 'Refresh',
    import_add_new : 'What do you want to add?',
    import_successful_add_new : 'Import has been successful!',
    admin_import_header : 'All rows of imported data:',
    admin_approve_imports : 'Click to approve imports',
    import_type_authors : 'Authors',
    import_type_texts : 'Texts',
    import_type_editions : 'Editions',
    import_error : 'Data has not been imported or the data imported is empty',
    import_databtn : 'Imported data',
    latest_editsbtn : 'Latest edits',
    admin_header : 'Admin',
    undoEditBtn : 'Undo all',
    successfulEdit : 'Your edits have been successfully updated!',
    homeBtn : 'Home',
    detailedSearchBtn : 'Detailed Search',
    importDataBtn : 'Import',
    adminBtn : 'Admin',
    latestAdditions : 'Latest Additions',
    author_q : 'Q Number (wikidata)',
    text_q : 'Q Number (wikidata)',
    text_author_q : 'Author Q Number',
    }
    
    export default labels;